### ISSUE TITLE
Question: How can I keep the same onion url between restarts?

### ISSUE THREAD

**Issue by sz55net** [kickscondor/granax#1]

**Comment by kickscondor** [comment]
The onion URL is stored in the database - along with its private key - so it should reload on subsequent restarts.

I take it... that's not happening for you?

**Comment by kickscondor** [comment]
Oh wait - I'm sorry - I thought this was a comment in the [Fraidycat](/kickscondor/fraidycat) issues!

Here is the relevant code I've used:

      const tor = require('@kickscondor/granax')();
      tor.on('ready', async () => {
        let opts = await local.localGet('tor-options', {})
        tor.createHiddenService('127.0.0.1:7547', opts, (err, result) => {
          if (result.privateKey) {
            local.localSet('tor-options', result.privateKey)
          }
          local.onionId = result.serviceId
          console.info(`Tor URL: ${result.serviceId}.onion`)
        })
      })

In this case, the `local.localGet` call returns a saved private key - or an empty dictionary `{}` if the private key doesn't yet exist.

The `local.localSet` call saves the private key. The `local.onionId` is where I keep the ID that will be used in the browser.

Hope that helps.

**Comment by CryptoGrampy** [comment]
If anyone else reads this and is still confused, you save the private key object that gets output when you create the hidden service for the first time (just console log the result.privateKey JSON), save it somewhere, and then pass it back in as an opt the second time around:

for example:
```javascript
let opts = {
  "keyType":"ED25519-V3",
  "keyBlob":"EYXZc9fW1J5jvW9Jbmr4tbXYmzVXrWxIawlkjsadflkjwaelkjfwalkjfeUZxDofeJJJJAJJALKJnOCdBBBDKg", 
}

torApp.createHiddenService('127.0.0.1:80', opts, (err, result) => {
  console.info(`Service URL: ${result.serviceId}.onion`);
  console.info(`Private Key: ${result.privateKey}`);
});

```
